In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv(r"C:\Users\Hello\Downloads\Weather_Data.csv")

In [4]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.3,-3.5,18,9,25.0,98.67,Clear
1,1/1/2012 1:00,7.4,2.8,20,24,24.1,99.37,Rain
2,1/1/2012 2:00,15.7,13.4,21,26,25.0,99.84,Cloudy
3,1/1/2012 3:00,4.9,-2.6,27,15,24.1,100.94,Mainly Clear
4,1/1/2012 4:00,-13.4,-19.7,30,4,25.0,102.32,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear
8782,9/30/2012 8:00,-6.3,-13.5,99,15,24.1,101.90,Cloudy
8783,9/30/2012 9:00,24.5,14.7,100,11,25.0,102.98,Mostly Cloudy

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [6]:
data.describe()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

In [7]:
data.shape

(8784, 8)

In [8]:
#1) Find all the unique 'Wind Speed' values in the data.
x=data["Wind Speed_km/h"].unique()

In [9]:
x

array([ 9, 24, 26, 15,  4,  0, 19, 17, 11, 22, 35, 13, 20,  6,  7, 30, 32,
       41, 39, 28, 44, 33, 37, 52, 46,  2, 50, 48, 57, 63, 43, 83, 70, 54],
      dtype=int64)

In [10]:
x=data["Wind Speed_km/h"].nunique()

In [10]:
x

34

In [11]:
#2) Find the number of times when the 'Weather is exactly Clear'.
c=data.loc[data["Weather"]=="Clear",["Weather"]].value_counts()

In [12]:
c

Weather
Clear      1326
dtype: int64

In [13]:
#3) ) Find the number of times when the 'Wind Speed was exactly 4 km/h'. 
x=data.loc[data["Wind Speed_km/h"]==4,["Wind Speed_km/h"]]

In [14]:
x

      Wind Speed_km/h
4                   4
23                  4
49                  4
84                  4
95                  4
...               ...
8736                4
8744                4
8754                4
8758                4
8768                4

[474 rows x 1 columns]

In [15]:
len(x)

474

In [16]:
#4) Find out all the Null Values in the data
x=data.isnull().sum()

In [17]:
x

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [18]:
#5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.
data1=data.rename(columns={"Weather":"Weather Condition"})

In [19]:
data1

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.3,-3.5,18,9,25.0,98.67,Clear
1,1/1/2012 1:00,7.4,2.8,20,24,24.1,99.37,Rain
2,1/1/2012 2:00,15.7,13.4,21,26,25.0,99.84,Cloudy
3,1/1/2012 3:00,4.9,-2.6,27,15,24.1,100.94,Mainly Clear
4,1/1/2012 4:00,-13.4,-19.7,30,4,25.0,102.32,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear
8782,9/30/2012 8:00,-6.3,-13.5,99,15,24.1,101.90,Cloudy
8783,9/30/2012 9:00,24.5,14.7,100,11,25.0,102.98,Mostly Cloudy

In [20]:
#6) What is the mean 'Visibility' ?
x=data["Visibility_km"].mean()

In [21]:
x

27.664446721311478

In [22]:
#7) What is the Standard Deviation of 'Pressure' in this data? 
x=data["Press_kPa"].std()

In [23]:
x

0.8440047459486459

In [24]:
#8) What is the Variance of 'Relative Humidity' in this data 
x=data["Rel Hum_%"].var()

In [25]:
x

286.2485501985015

In [26]:
#9) Find all instances when 'Snow' was recorded. 
x=data1.loc[data1["Weather Condition"]=="Snow"]

In [27]:
x

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
11,1/1/2012 11:00,-6.2,-9.6,37,35,4.8,101.56,Snow
70,3/1/2012 22:00,-4.0,-6.6,62,22,16.1,100.48,Snow
73,4/1/2012 1:00,2.3,-3.4,64,35,25.0,103.43,Snow
105,5/1/2012 9:00,-1.8,-4.2,73,15,6.4,101.28,Snow
112,5/1/2012 16:00,1.7,-0.3,75,6,9.7,101.47,Snow
...,...,...,...,...,...,...,...,...
8573,9/22/2012 13:00,-6.0,-10.2,82,19,16.1,101.71,Snow
8650,9/25/2012 18:00,-4.6,-6.6,52,4,12.9,100.48,Snow
8671,9/26/2012 15:00,-5.9,-10.5,60,13,16.1,101.01,Snow
8713,9/28/2012 1:00,-5.2,-7.8,72,33,4.0,101.33,Snow
8734,9/28/2012 8:00,0.7,-1.2,79,30,8.0,101.22,Snow

In [28]:
#10)  Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'. 
x=data.loc[(data["Wind Speed_km/h"]>24)&(data["Visibility_km"]==25),["Wind Speed_km/h","Visibility_km"]]

In [29]:
x

      Wind Speed_km/h  Visibility_km
2                  26           25.0
73                 35           25.0
126                39           25.0
158                26           25.0
184                44           25.0
...               ...            ...
8707               33           25.0
8714               26           25.0
8738               28           25.0
8745               28           25.0
8776               43           25.0

[308 rows x 2 columns]

In [30]:
#11) What is the Mean value of each column against each 'Weather Condition 
x=data1.groupby("Weather Condition")
x[["Temp_C","Dew Point Temp_C","Rel Hum_%","Wind Speed_km/h","Visibility_km","Press_kPa"]].mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,
Clear,6.825716,0.089367,67.127451,10.557315,30.153243,101.084495
Cloudy,7.970544,2.375810,67.349537,16.127315,26.625752,101.056852
Drizzle,7.353659,5.504878,69.048780,16.097561,17.931707,101.099268
"Drizzle,Fog",8.067500,7.033750,70.062500,11.862500,5.257500,100.820750
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,52.000000,20.000000,4.000000,99.440000
"Drizzle,Snow",1.050000,0.150000,44.000000,14.000000,10.500000,100.490000
"Drizzle,Snow,Fog",0.693333,0.120000,69.800000,15.533333,5.513333,100.971333
Fog,4.303333,3.159333,66.466667,7.946667,6.248000,101.149400
Freezing Drizzle,-5.657143,-8.000000,68.857143,16.571429,9.200000,101.070000
"Freezing Drizzle,Fog",-2.533333,-4.183333,64.000000,17.000000,5.266667,100.851667
"Freezing Drizzle,Haze",-5.433333,-8.000000,63.333333,10.333333,2.666667,101.136667
"Freezing Drizzle,Snow",-5.109091,-7.072727,62.454545,16.272727,5.872727,100.380909
Freezing Fog,-7.575000,-9.250000,68.000000,4.750000,0.650000,101.222500
Freezing Rain,-3.885714,-6.078571,60.785714,19.214286,8.242857,101.500714
"Freezing Rain,Fog",-2.225000,-3.750000,52.750000,15.500000,7.550000,100.267500
"Freezing Rain,Haze",-4.900000,-7.450000,63.000000,7.500000,2.400000,100.265000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,65.000000,28.000000,8.000000,98.330000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,92.000000,32.000000,4.800000,102.520000
Haze,-0.200000,-2.975000,69.625000,10.437500,7.831250,100.805625
Mainly Clear,12.558927,4.581671,68.020893,14.144824,34.264862,101.040940
"Moderate Rain,Fog",1.700000,0.800000,89.000000,17.000000,6.400000,100.450000
Moderate Snow,-5.525000,-7.250000,67.500000,33.750000,0.750000,100.760000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,81.500000,40.000000,0.600000,102.215000
Mostly Cloudy,10.574287,3.131174,67.214113,15.813920,31.253842,101.051054
Rain,9.786275,7.042810,67.614379,19.254902,18.856536,101.051797
Rain Showers,13.722340,9.187766,68.335106,17.132979,22.816489,101.020106
"Rain Showers,Fog",12.800000,12.100000,31.000000,13.000000,6.400000,99.800000
"Rain Showers,Snow Showers",2.150000,-1.500000,68.500000,22.500000,21.700000,101.080000
"Rain,Fog",8.273276,7.219828,66.818966,14.793103,6.873276,100.991983
"Rain,Haze",4.633333,2.066667,57.666667,11.666667,6.700000,100.716667
"Rain,Ice Pellets",0.600000,-0.600000,54.000000,24.000000,9.700000,101.880000
"Rain,Snow",1.055556,-0.566667,66.944444,28.388889,11.672222,100.895000
"Rain,Snow Grains",1.900000,-2.100000,87.000000,26.000000,25.000000,100.870000
"Rain,Snow,Fog",0.800000,0.300000,61.000000,9.000000,6.400000,102.480000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,72.500000,23.250000,6.000000,101.170000
Snow,-4.524103,-7.623333,66.402564,20.038462,11.171795,101.077205
Snow Pellets,0.700000,-6.400000,66.000000,35.000000,2.400000,99.560000
Snow Showers,-3.506667,-7.866667,65.600000,19.233333,20.158333,100.999333
"Snow Showers,Fog",-10.675000,-11.900000,63.750000,13.750000,7.025000,100.770000
"Snow,Blowing Snow",-5.410526,-7.621053,72.631579,34.842105,4.105263,101.032105
"Snow,Fog",-5.075676,-6.364865,70.459459,17.324324,4.537838,101.194865
"Snow,Haze",-4.020000,-6.860000,66.000000,5.000000,4.640000,100.360000
"Snow,Ice Pellets",-1.883333,-3.666667,74.000000,23.833333,7.416667,100.746667
Thunderstorms,24.150000,19.750000,56.500000,7.500000,24.550000,101.375000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,82.000000,9.000000,2.400000,101.400000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,58.000000,15.000000,3.200000,99.940000
"Thunderstorms,Rain",20.433333,18.533333,71.666667,15.666667,19.833333,101.536667
"Thunderstorms,Rain Showers",20.037500,17.618750,68.437500,18.312500,15.893750,100.976875
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,58.666667,19.666667,9.700000,100.806667
"Thunderstorms,Rain,Fog",20.600000,18.600000,42.000000,19.000000,4.800000,100.450000

In [31]:
#12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?
x=data1["Weather Condition"].min()

In [32]:
x

'Clear'

In [33]:
x=data1["Weather Condition"].max()

In [34]:
x

'Thunderstorms,Rain,Fog'

In [35]:
#13) Show all the Records where Weather Condition is Fog.

In [36]:
c

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
13,1/1/2012 13:00,9.5,7.8,40,13,6.4,100.90,Fog
53,3/1/2012 5:00,-3.6,-4.3,57,7,9.7,101.32,Fog
136,6/1/2012 16:00,14.8,13.5,80,19,9.7,100.86,Fog
197,9/1/2012 5:00,2.1,0.7,43,11,8.0,101.44,Fog
278,12/1/2012 14:00,1.2,0.6,70,13,6.4,103.22,Fog
...,...,...,...,...,...,...,...,...
8475,9/18/2012 11:00,6.2,5.4,56,7,4.8,102.03,Fog
8511,9/19/2012 22:00,15.7,15.4,66,7,8.0,101.93,Fog
8518,9/19/2012 8:00,-2.9,-4.5,68,6,6.4,100.41,Fog
8537,9/20/2012 3:00,-0.5,-2.1,74,7,4.0,100.81,Fog
8771,9/30/2012 19:00,12.8,12.2,91,19,4.8,100.60,Fog

In [37]:
#14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.
x=data.loc[(data["Weather"]=="Clear")|(data["Visibility_km"]>40),["Date/Time","Temp_C","Dew Point Temp_C","Rel Hum_%","Wind Speed_km/h","Visibility_km","Press_kPa","Weather"]]

In [38]:
x

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.3,-3.5,18,9,25.0,98.67,Clear
9,1/1/2012 9:00,20.0,3.8,35,17,48.3,100.11,Clear
16,1/1/2012 16:00,23.8,17.6,42,9,25.0,100.52,Clear
17,1/1/2012 17:00,-6.8,-9.8,42,20,48.3,100.76,Mainly Clear
18,1/1/2012 18:00,2.3,-2.4,42,6,48.3,101.05,Cloudy
...,...,...,...,...,...,...,...,...
8774,9/30/2012 21:00,23.0,14.7,92,13,48.3,101.93,Mostly Cloudy
8777,9/30/2012 3:00,9.3,5.8,95,9,48.3,101.25,Mainly Clear
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear

In [39]:
#15) A. 'Weather is Clear' and 'Relative Humidity is greater than 50' 
x=data.loc[(data["Weather"]=="Clear")|(data["Rel Hum_%"]>50)]

In [40]:
x

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.3,-3.5,18,9,25.0,98.67,Clear
9,1/1/2012 9:00,20.0,3.8,35,17,48.3,100.11,Clear
16,1/1/2012 16:00,23.8,17.6,42,9,25.0,100.52,Clear
19,1/1/2012 19:00,-12.7,-17.2,43,17,48.3,101.16,Clear
22,1/1/2012 22:00,14.1,8.3,45,9,25.0,101.05,Clear
...,...,...,...,...,...,...,...,...
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy
8781,9/30/2012 7:00,1.5,-6.3,99,30,24.1,101.48,Clear
8782,9/30/2012 8:00,-6.3,-13.5,99,15,24.1,101.90,Cloudy
8783,9/30/2012 9:00,24.5,14.7,100,11,25.0,102.98,Mostly Cloudy

In [41]:
#15) b.'Visibility is above 40'.
x=data.loc[data["Visibility_km"]>40]

In [42]:
x

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
9,1/1/2012 9:00,20.0,3.8,35,17,48.3,100.11,Clear
17,1/1/2012 17:00,-6.8,-9.8,42,20,48.3,100.76,Mainly Clear
18,1/1/2012 18:00,2.3,-2.4,42,6,48.3,101.05,Cloudy
19,1/1/2012 19:00,-12.7,-17.2,43,17,48.3,101.16,Clear
23,1/1/2012 23:00,29.5,16.8,45,4,48.3,101.07,Mainly Clear
...,...,...,...,...,...,...,...,...
8759,9/29/2012 9:00,-2.1,-10.9,86,24,48.3,101.41,Mostly Cloudy
8774,9/30/2012 21:00,23.0,14.7,92,13,48.3,101.93,Mostly Cloudy
8777,9/30/2012 3:00,9.3,5.8,95,9,48.3,101.25,Mainly Clear
8779,9/30/2012 5:00,1.4,-3.7,97,22,48.3,100.16,Cloudy
8780,9/30/2012 6:00,-4.6,-9.5,98,11,48.3,101.46,Mostly Cloudy